name: Hourly API Call

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Make API POST request
      run: |
        curl -X POST https://mtsranks.vercel.app/store-data
