name: Hourly API Call

on:
  schedule:
    - cron: '0 * * * *'  # Runs at the top of every hour
  push:
    branches:
      - main

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:

    - name: Make API POST request
      id: api_call
      run: |
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://mtsranks.vercel.app/store-data)
        echo "API_RESPONSE_CODE=$RESPONSE" >> $GITHUB_ENV

    - name: Send Notification to Line on Failure
      if: env.API_RESPONSE_CODE != '200'
      env:
        LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
      run: |
        MESSAGE="MiRank Hourly Update: Failed"
        curl -X POST -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" -F "message=$MESSAGE" https://notify-api.line.me/api/notify
