name: Manual Trigger Test

on:
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest

    steps:
    - name: Make API POST request
      run: |
        curl -X POST https://mtsranks.vercel.app/store-data
